### ISSUE TITLE
IP-Tables dont get created

### ISSUE THREAD

**Issue by moswed** [tozd/docker-external-ip#2]
i've just tried your container after searching hours for a solution to specify a specific outbound Interface.

i started your container like in the example: 

` docker run --detach --restart=always --net=host --cap-add=NET_ADMIN --cap-add=NET_RAW --volume /var/run/docker.sock:/var/run/docker.sock tozd/external-ip
`

then i started my postfix with the following docker-compose File.

```
version: "3"
services:

  mailserver:
    image: instrumentisto/postfix
    ports:
    - "xx.xx.xx.139:25:25"
    - "xx.xx.xx.139:465:465"
    - "xx.xx.xx.139:587:587"
    volumes:
    - ./main.cf:/etc/postfix/main.cf
    environment:
      EXTERNAL_IP: xx.xx.xx.139
    networks:
    - backend

networks:
  backend:
    external:
      name: backend
```

But no iptable rules or chains get created and the mails still comes from te default Interface. 
Do i miss something?

Docker-Engine Version: 18.03.0-ce
Docker-API Version: 1.37
Docker-compose Version: 1.20.1

**Comment by mitar** [comment]
Not sure what:

```
networks:
  backend:
    external:
      name: backend
```

does. But your mail container does not have to (should not?) run on host network, but a normal internal Docker network.
